### ISSUE TITLE
ERROR : Expected primary expression in solidity 0.8.19

### ISSUE THREAD

**Issue by KhalilSayah** [thetatoken/theta-nft-demo#1]
Hello, i'm working on NFT Project on Theta network and when coping the nft.sol to iheritate from it, i get this error in the line 399, in the "byte" key word
![image](https://user-images.githubusercontent.com/29178160/235244141-12fbb9ff-153b-4246-8bb0-2009d5a9598f.png)

**Comment by Fredrik-Rafn** [comment]
Use `bytes1` instead of `byte`.

> The type `byte` has been removed. It was an alias of `bytes1`.

Source: https://docs.soliditylang.org/en/v0.8.3/080-breaking-changes.html#silent-changes-of-the-semantics

**Comment by jieyilong** [comment]
Just updated the contract to support Solidity 0.8.x
